### ISSUE TITLE
Issue in rpm packages version comparison. 

### ISSUE THREAD

**Issue by SharanPrasad** [knqyf263/go-rpm-version#4]
To the respective owner of this repo,

currentPackageVersion := rpmversion.NewVersion("1-82.module+el8.10.0+22397+e3c95ba6.x86_64.rpm")
expectedPackageVersion := rpmversion.NewVersion("1.2.2-7.module+el8.4.0+11310+8c67a752.x86_64.rpm")

When comparing RPM packages like above , we are getting false results.

It is detecting the lower version(expectedPackageVersion) as higher version.
Here in above example "1.2.2-7.module+el8.4.0+11310+8c67a752.x86_64.rpm" is detected as higher version.
But in actual currentPackageVersion("1-82.module+el8.10.0+22397+e3c95ba6.x86_64.rpm") should have been detected as higher version.

**Comment by knqyf263** [comment]
1.2.2 is newer than 1, so the result looks correct. Can you explain the reason why you think it's wrong?

**Comment by SharanPrasad** [comment]
But according to redhat currentPackageVersion is latest version compared to expectedPackageVersion.
Looks like they do not follow the standard structure of package name which is "name-version-release.architecture.rpm".
We have been informed to check and use release version comparison as well .
 
I reached redhat support too to understand why different naming convention has been followed.
Here is what they have to say for your reference:

Here are the package versions you listed:

    P1- containers-common-1-82.module+el8.10.0+22397+e3c95ba6.x86_64.rpm
    P2- containers-common-1.2.2-10.module+el8.5.0+11808+4e1db630.x86_64.rpm

Mapping the guide to those names, despite the upstream version seemingly
out of order, you can see the RPM Release Version incrementing.

If you look at the package over time, you can see the RPM Release Version
continuously increasing. For example, start here, and you can observe this:

    https://access.redhat.com/downloads/content/containers-common/1-82.module+el8.10.0+22397+e3c95ba6/x86_64/fd431d51/package-changelog

Something else we can see is that the Epoch tag is incremented
in this package. The epoch tag is the most important tiebreaker to
consider. See:

    https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_epoch_tag

Looking at the package browser, not only does the RPM Release Version
suggest that P1 is newer than P2, but the epoch also increases. For
example, on my test system, I can see that P1 is has Epoch tag 2:

    # dnf info containers-common-1-82.module+el8.10.0+22397+e3c95ba6

    Installed Packages
    Name         : containers-common
    Epoch        : 2
    Version      : 1
    Release      : 82.module+el8.10.0+22397+e3c95ba6

On this system, the version you note as P2 has aged out, but I can see that
it is Epoch tag 1 in the package browser:

    https://access.redhat.com/downloads/content/containers-common/1.2.2-10.module+el8.5.0+11808+4e1db630/x86_64/fd431d51/package-changelog

**Comment by knqyf263** [comment]
You can see the result by rpmdev-vercmp from [RPM Development Tools](https://fedoraproject.org/wiki/Rpmdevtools).

```
$ dnf -y install rpmdevtools
$ rpmdev-vercmp 1-82.module+el8.10.0+22397+e3c95ba6 1.2.2-7.module+el8.4.0+11310+8c67a752
1-82.module+el8.10.0+22397+e3c95ba6 < 1.2.2-7.module+el8.4.0+11310+8c67a752
```

The version string must include an epoch.

```
# rpmdev-vercmp 2:1-82.module+el8.10.0+22397+e3c95ba6 1:1.2.2-7.module+el8.4.0+11310+8c67a752
2:1-82.module+el8.10.0+22397+e3c95ba6 > 1:1.2.2-7.module+el8.4.0+11310+8c67a752
```

This library works as expected.
https://go.dev/play/p/TxzpmtjIXhp

**Comment by SharanPrasad** [comment]
Got it 
thank you so much for the help
